### ISSUE TITLE
FM narrow indication FMN is hard to distinguish

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#102]
Feedback from one operator that the display of FM Narrow is sub optimal

Alternative suggestions were FMn and nFM

**Comment by rogerclarkmelbourne** [comment]
It may be better to include bandwidth on the right side of the screen to separate it from the FM text

**Comment by ajorg** [comment]
![narrow](https://user-images.githubusercontent.com/260569/69777838-d19fec80-1156-11ea-9684-4b3ced8fcd66.png)

Is something like this better, with an N or W on the right side?

**Comment by ajorg** [comment]
I don't think there's enough room for 12.5kHz, and just 12.5 or 25 would be confusing too.

**Comment by rogerclarkmelbourne** [comment]
I think its a bit confusing just to have a "N"

Perhaps move the power indication so that rater than it being centered its always 8 pixels to the left of its current location.  (or some other distance)

Then this would leave more space on the right

**Comment by ajorg** [comment]
I think I can make that happen.

**Comment by rogerclarkmelbourne** [comment]
What will you put on the right hand side ?  "12.5kHz"  or "25kHz" ?

**Comment by rogerclarkmelbourne** [comment]
I did think of "WB" / "NB" but 25kHz is not really "wide"

**Comment by ajorg** [comment]
I experimented with "12.5kHz" but there really isn't enough room. There's space for about 21 characters, and `FM CTR250mW12.5kHz99%` is 21 characters and clearly too dense.

The more I try to make this work the more I think `FMN`, `FMn`, `NFM`, or `nFM` really is the better way to go. Mostly because you're right that `WB` is not accurate.

I could go with showing `NB` on the right *only* when using 12.5kHz FM, but I'd rather fit `L` on the right when locked.

Or... icons, which frankly I'm not excited about.

**Comment by rogerclarkmelbourne** [comment]
Daniel is currently working on extending the fonts, so you could probably have a special symbol for this (though I don't know what)

**Comment by f1rmb** [comment]
What about bold font for wide, and regular for narrow.
Of course, our 8x6 bold isn't bold ATM.

Cheers.

---
73 de Daniel, F1RMB
http://f1rmb.blog.free.fr

Le jeu. 28 nov. 2019 06:36, Andrew Jorgensen <notifications@github.com> a
écrit :

**Comment by ajorg** [comment]
Honestly, I think `FMN` or `NFM` for the mode on the left is the right solution. But I'm happy to try to implement something else if people would really prefer something else.

I'm used to treating narrowband FM as a separate mode from other radios I've owned.

**Comment by rogerclarkmelbourne** [comment]
NFM would make it more obvious

**Comment by ajorg** [comment]
I've got patches ready for either of these:

![nfm](https://user-images.githubusercontent.com/260569/69842720-2d32ae80-1219-11ea-9436-0a1487a53261.png)
![nfm-lower](https://user-images.githubusercontent.com/260569/69842722-302d9f00-1219-11ea-900b-f7d58bd10702.png)

Maybe worth noting that at least on *my* radio the LCD is places so that I can only see about half of the `N` unless I have the screen turned a bit away to my left.

PS: Thanks for the screengrab feature. It's excellent!

**Comment by rogerclarkmelbourne** [comment]
I'm closing all enhancement issues
