### ISSUE TITLE
DM-1801 tone/buzz on Rx

### ISSUE THREAD

**Issue by da3020** [rogerclarkmelbourne/OpenGD77#877]
Here is some bug for 1801 in this release: quiet buz during Rx on two acoustic harmonics 875 Hz and 1750 Hz.

**Comment by rogerclarkmelbourne** [comment]
I know of one other radio which has this problem, but because my DM-1801 does not have that fault, its impossible for me to debug what is causing it.

BTW. Are you certain of those exact frequencies (875Hz and 1750Hz), or is this an estimate of the frequency.
As 1750Hz is exactly the "Tone burst" frequency for old FM repeaters.

**Comment by da3020** [comment]
> Are you certain

I see two peaks on acoustic spectrum analyzer quite precise: 875Hz and 1750Hz almost the same amplitude.
Also, these buzz disappears when holding monitor button.

**Comment by rogerclarkmelbourne** [comment]
Is this on FM ?

Do you have any CTCSS on that channel

Monitor mode turns of CTCSS/DCS

**Comment by rogerclarkmelbourne** [comment]
No reply from OP in nearly 3 months. Hence I'm closing this issue

Its possible it has now been fixed by various other changes made over the last 3 months e.g.

Try this version

https://github.com/rogerclarkmelbourne/OpenGD77/files/6072087/OpenGD77_20210303855.zip
